name: github-actions-demo

on:
  push:
    branches:
      - main
      
jobs:
  run-batch:
    runs-on: local

    steps:
        
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: run batch script
      run: |
              cd C:\Users\C9952825\hello.bat
              
              
    - name: Configure Git
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Push to Bitbucket
      run: |
        mkdir shiva
        cd shiva
        git add .
        git commit -m "push to bitbucket"
        git clone https://appsint:dc2cce27aa5846d5482dccd1ab370673@bitbucket-prod.tcc.etn.com/scm/~e0020874/nsi_48v_dcdcplatform.git
        git status
        dir
